services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
      - laravel
    depends_on:
      - db
      - redis

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - laravel:/var/lib/mysql
    environment:
      MYSQL_DATABASE: delivery_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  laravel:

networks:
  laravel:
    driver: bridge